### ISSUE TITLE
是否支持新版setup语法糖vue3文件的覆盖率呢

### ISSUE THREAD

**Issue by okkidev03** [canyon-project/canyon#17]
是否支持新版setup语法糖vue3文件的覆盖率呢

**Comment by zhangtao25** [comment]
支持的，参考 https://github.com/canyon-project/canyon/blob/e32dd4f97983e3fc3b22eb88160262badf04ad88/examples/vite-vue/vite.config.ts#L9

**Comment by okkidev03** [comment]
插桩工具支持我知道，就是这个报告的映射不知道准不准确了

**Comment by zhangtao25** [comment]
除了babel以外的插桩其实都是实验性的

**Comment by okkidev03** [comment]
vue-webpack构建模式使用的babel插桩，vue报告的映射是准确的吗

**Comment by zhangtao25** [comment]
> vue-webpack构建模式使用的babel插桩，vue报告的映射是准确的吗

babel的都是准确的，我们内部进行了大量验证。
