### ISSUE TITLE
新建项目->服务提供商列表为空，如何设置服务提供商的数据

### ISSUE THREAD

**Issue by imath60** [canyon-project/canyon#19]
新建项目，服务提供商下拉菜单为空，如图所示：
![image](https://github.com/canyon-project/canyon/assets/6263682/062ca10b-362d-4b9e-8dc9-7e8d677efb72)
查看代码使用的是GitProvider，如何初始化各字段数据。
![image](https://github.com/canyon-project/canyon/assets/6263682/887cefc7-453e-4fa1-b78a-a3808764f783)

**Comment by zhangtao25** [comment]
INSERT INTO public."GitProvider" (id, url, "clientID", "clientSecret", type, name, disabled) VALUES ('tripgl', 'https://gitlab.com', 'xxxxxxxxx', 'xxxxxxxxx', 'gitlab', 'Trip.com GitLab', false);

**Comment by zhangtao25** [comment]
clientID和clientSecret随便填，尚未实现，gitlab鉴权需要配置PRIVATE_TOKEN来鉴权gitlab接口
