### ISSUE TITLE
Support Configuration of Interval Reporting Time via Babel Plugin

### ISSUE THREAD

**Issue by JINGXUANLLL** [canyon-project/canyon#29]
Hi there,

I am currently utilizing your Babel plugin for my project, I would like to request a feature that allows users to configure the interval reporting time directly through the Babel plugin settings.

**Comment by zhangtao25** [comment]
https://github.com/canyon-project/canyon/commit/068ec3a895933ce17bb2c09e08832aaf14f39a14
