### ISSUE TITLE
What are the good solutions for nodejs applications?

### ISSUE THREAD

**Issue by linfeizhang23** [canyon-project/canyon#6]

**Comment by zhangtao25** [comment]
For nodejs applications, you can choose to directly use nyc for instrumentation

Scheme 1
Regularly perform coverage sampling, save it to a local coverage file, and then report it through a script

Scheme 2
Add a coverage interface to the application and throw coverage data through the access interface

Be careful
After code insertion in Nodejs applications, memory usage will increase, and attention should be paid to whether the probe counter for coverage will exceed the maximum number type value in JavaScript
